services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=resona_db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'