CREATE TABLE if not exists email_verification_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_email_verification_tokens PRIMARY KEY (id)
);

CREATE TABLE if not exists jingle_schedules
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by VARCHAR(255)                            NOT NULL,
    store_id   BIGINT                                  NOT NULL,
    active     BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT pk_jingle_schedules PRIMARY KEY (id)
);

CREATE TABLE if not exists jingle_slots
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    play_time          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    jingle_id          BIGINT                                  NOT NULL,
    jingle_schedule_id BIGINT                                  NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_jingle_slots PRIMARY KEY (id)
);

CREATE TABLE if not exists jingle_stores
(
    jingle_id BIGINT NOT NULL,
    store_id  BIGINT NOT NULL,
    CONSTRAINT pk_jingle_stores PRIMARY KEY (jingle_id, store_id)
);

CREATE TABLE if not exists jingles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    voice              VARCHAR(255)                            NOT NULL,
    category           VARCHAR(255)                            NOT NULL,
    start_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    repeating_time     VARCHAR(255)                            NOT NULL,
    announcement_text  VARCHAR(500)                            NOT NULL,
    speed              DOUBLE PRECISION                        NOT NULL,
    file_url           VARCHAR(255)                            NOT NULL,
    requested_to_pause BOOLEAN DEFAULT FALSE                   NOT NULL,
    pause_approved     BOOLEAN DEFAULT FALSE                   NOT NULL,
    organization_id    BIGINT,
    CONSTRAINT pk_jingles PRIMARY KEY (id)
);

CREATE TABLE if not exists musics
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_url   VARCHAR(255)                            NOT NULL,
    mood       VARCHAR(255),
    atmosphere VARCHAR(255),
    CONSTRAINT pk_musics PRIMARY KEY (id)
);

CREATE TABLE if not exists organizations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by       VARCHAR(255)                            NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by       VARCHAR(255)                            NOT NULL,
    company_name     VARCHAR(160)                            NOT NULL,
    business_type    VARCHAR(160)                            NOT NULL,
    music_provider   VARCHAR(100)                            NOT NULL,
    music_atmosphere VARCHAR(255),
    current_feel     VARCHAR(255)                            NOT NULL,
    music_mood       VARCHAR(128)                            NOT NULL,
    playtime_window  VARCHAR(128)                            NOT NULL,
    CONSTRAINT pk_organizations PRIMARY KEY (id)
);

CREATE TABLE if not exists outgoing_requests
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by           VARCHAR(255)                            NOT NULL,
    url                  VARCHAR(255)                            NOT NULL,
    method               VARCHAR(255)                            NOT NULL,
    request_body         VARCHAR(255)                            NOT NULL,
    response_status_code SMALLINT                                NOT NULL,
    response_body        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_outgoing_requests PRIMARY KEY (id)
);

CREATE TABLE if not exists store_analytics_data
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    snapshot_date date,
    store_name    VARCHAR(255)                            NOT NULL,
    play_minutes  INTEGER                                 NOT NULL,
    CONSTRAINT pk_store_analytics_data PRIMARY KEY (id)
);

CREATE TABLE if not exists stores
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    location        VARCHAR(255),
    email           VARCHAR(254)                            NOT NULL,
    active          BOOLEAN DEFAULT FALSE                   NOT NULL,
    music_link      VARCHAR(255),
    music_link_uuid UUID,
    organization_id BIGINT                                  NOT NULL,
    user_id         BIGINT,
    CONSTRAINT pk_stores PRIMARY KEY (id)
);

CREATE TABLE if not exists users
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at                  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by                  VARCHAR(255)                            NOT NULL,
    created_at                  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by                  VARCHAR(255)                            NOT NULL,
    email                       VARCHAR(254)                            NOT NULL,
    password                    VARCHAR(255),
    role                        VARCHAR(20)                             NOT NULL,
    email_changed               BOOLEAN DEFAULT FALSE                   NOT NULL,
    email_verified              BOOLEAN DEFAULT FALSE                   NOT NULL,
    enabled                     BOOLEAN DEFAULT TRUE                    NOT NULL,
    full_name                   VARCHAR(255),
    company_role                VARCHAR(255),
    email_verification_token_id BIGINT,
    organization_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE jingle_schedules
    ADD CONSTRAINT uc_jingle_schedules_store UNIQUE (store_id);

ALTER TABLE organizations
    ADD CONSTRAINT uc_organizations_companyname UNIQUE (company_name);

ALTER TABLE stores
    ADD CONSTRAINT uc_stores_musiclink UNIQUE (music_link);

ALTER TABLE stores
    ADD CONSTRAINT uc_stores_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email_verification_token UNIQUE (email_verification_token_id);

ALTER TABLE jingles
    ADD CONSTRAINT FK_JINGLES_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE jingle_schedules
    ADD CONSTRAINT FK_JINGLE_SCHEDULES_ON_STORE FOREIGN KEY (store_id) REFERENCES stores (id);

ALTER TABLE jingle_slots
    ADD CONSTRAINT FK_JINGLE_SLOTS_ON_JINGLE FOREIGN KEY (jingle_id) REFERENCES jingles (id);

ALTER TABLE jingle_slots
    ADD CONSTRAINT FK_JINGLE_SLOTS_ON_JINGLE_SCHEDULE FOREIGN KEY (jingle_schedule_id) REFERENCES jingle_schedules (id);

ALTER TABLE stores
    ADD CONSTRAINT FK_STORES_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE stores
    ADD CONSTRAINT FK_STORES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_EMAIL_VERIFICATION_TOKEN FOREIGN KEY (email_verification_token_id) REFERENCES email_verification_tokens (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE jingle_stores
    ADD CONSTRAINT fk_jinsto_on_jingle FOREIGN KEY (jingle_id) REFERENCES jingles (id);

ALTER TABLE jingle_stores
    ADD CONSTRAINT fk_jinsto_on_store FOREIGN KEY (store_id) REFERENCES stores (id);