CREATE TABLE email_verification_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_email_verification_tokens PRIMARY KEY (id)
);

CREATE TABLE jingle_stores
(
    jingle_id BIGINT NOT NULL,
    store_id  BIGINT NOT NULL,
    CONSTRAINT pk_jingle_stores PRIMARY KEY (jingle_id, store_id)
);

CREATE TABLE jingles
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by        VARCHAR(255)                            NOT NULL,
    voice             VARCHAR(255)                            NOT NULL,
    category          VARCHAR(255)                            NOT NULL,
    start_date        date                                    NOT NULL,
    end_date          date                                    NOT NULL,
    duration          numeric(21,0)                           NOT NULL,
    announcement_text VARCHAR(500)                            NOT NULL,
    file_url          VARCHAR(255)                            NOT NULL,
    user_id           BIGINT,
    CONSTRAINT pk_jingles PRIMARY KEY (id)
);

CREATE TABLE music_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    icon_name   VARCHAR(255)                            NOT NULL,
    preview_url VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_music_types PRIMARY KEY (id)
);

CREATE TABLE outgoing_requests
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by           VARCHAR(255)                            NOT NULL,
    url                  VARCHAR(255)                            NOT NULL,
    method               VARCHAR(255)                            NOT NULL,
    request_body         VARCHAR(255)                            NOT NULL,
    response_status_code SMALLINT                                NOT NULL,
    response_body        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_outgoing_requests PRIMARY KEY (id)
);

CREATE TABLE stores
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_by      VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    location        VARCHAR(255),
    email           VARCHAR(254)                            NOT NULL,
    active          BOOLEAN DEFAULT FALSE                   NOT NULL,
    music_link      VARCHAR(255),
    music_link_uuid UUID,
    user_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_stores PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at                  TIMESTAMP WITHOUT TIME ZONE,
    updated_by                  VARCHAR(255),
    created_at                  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by                  VARCHAR(255)                            NOT NULL,
    company_name                VARCHAR(160)                            NOT NULL,
    business_type               VARCHAR(160)                            NOT NULL,
    music_provider              VARCHAR(100)                            NOT NULL,
    brand_identity              SMALLINT ARRAY                          NOT NULL,
    current_feel                SMALLINT ARRAY                          NOT NULL,
    space_purpose               VARCHAR(128)                            NOT NULL,
    playtime_window             VARCHAR(128)                            NOT NULL,
    onboarding_completed        BOOLEAN DEFAULT FALSE                   NOT NULL,
    password                    VARCHAR(255),
    role                        VARCHAR(20)                             NOT NULL,
    email                       VARCHAR(254)                            NOT NULL,
    email_verification_token_id BIGINT,
    email_verified              BOOLEAN DEFAULT FALSE                   NOT NULL,
    enabled                     BOOLEAN DEFAULT TRUE                    NOT NULL,
    full_name                   VARCHAR(255),
    company_role                VARCHAR(255),
    music_type_id               BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE music_types
    ADD CONSTRAINT uc_music_types_name UNIQUE (name);

ALTER TABLE stores
    ADD CONSTRAINT uc_stores_musiclink UNIQUE (music_link);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email_verification_token UNIQUE (email_verification_token_id);

ALTER TABLE jingles
    ADD CONSTRAINT FK_JINGLES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE stores
    ADD CONSTRAINT FK_STORES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_EMAIL_VERIFICATION_TOKEN FOREIGN KEY (email_verification_token_id) REFERENCES email_verification_tokens (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_MUSIC_TYPE FOREIGN KEY (music_type_id) REFERENCES music_types (id);

ALTER TABLE jingle_stores
    ADD CONSTRAINT fk_jinsto_on_jingle FOREIGN KEY (jingle_id) REFERENCES jingles (id);

ALTER TABLE jingle_stores
    ADD CONSTRAINT fk_jinsto_on_store FOREIGN KEY (store_id) REFERENCES stores (id);