CREATE TABLE if not exists email_verification_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by  VARCHAR(255)                            NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_email_verification_tokens PRIMARY KEY (id)
);

CREATE TABLE if not exists jingle_stores
(
    jingle_id BIGINT NOT NULL,
    store_id  BIGINT NOT NULL,
    CONSTRAINT pk_jingle_stores PRIMARY KEY (jingle_id, store_id)
);

CREATE TABLE if not exists jingles
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by         VARCHAR(255)                            NOT NULL,
    voice              VARCHAR(255)                            NOT NULL,
    category           VARCHAR(255)                            NOT NULL,
    start_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    duration           NUMERIC(21,0)                           NOT NULL,
    announcement_text  VARCHAR(500)                            NOT NULL,
    file_url           VARCHAR(255)                            NOT NULL,
    requested_to_pause BOOLEAN DEFAULT FALSE                   NOT NULL,
    pause_approved     BOOLEAN DEFAULT FALSE                   NOT NULL,
    organization_id    BIGINT,
    CONSTRAINT pk_jingles PRIMARY KEY (id)
);

CREATE TABLE if not exists music_types
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    icon_name   VARCHAR(255)                            NOT NULL,
    preview_url VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_music_types PRIMARY KEY (id)
);

CREATE TABLE if not exists organization_music_types
(
    music_type_id   BIGINT NOT NULL,
    organization_id BIGINT NOT NULL,
    CONSTRAINT pk_organization_music_types PRIMARY KEY (music_type_id, organization_id)
);

CREATE TABLE if not exists organizations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    company_name    VARCHAR(160)                            NOT NULL,
    business_type   VARCHAR(160)                            NOT NULL,
    music_provider  VARCHAR(100)                            NOT NULL,
    brand_identity  SMALLINT ARRAY                          NOT NULL,
    current_feel    SMALLINT ARRAY                          NOT NULL,
    space_purpose   VARCHAR(128)                            NOT NULL,
    playtime_window VARCHAR(128)                            NOT NULL,
    CONSTRAINT pk_organizations PRIMARY KEY (id)
);

CREATE TABLE if not exists outgoing_requests
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by           VARCHAR(255)                            NOT NULL,
    url                  VARCHAR(255)                            NOT NULL,
    method               VARCHAR(255)                            NOT NULL,
    request_body         VARCHAR(255)                            NOT NULL,
    response_status_code SMALLINT                                NOT NULL,
    response_body        VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_outgoing_requests PRIMARY KEY (id)
);

CREATE TABLE if not exists stores
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by      VARCHAR(255)                            NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    location        VARCHAR(255),
    email           VARCHAR(254)                            NOT NULL,
    active          BOOLEAN DEFAULT FALSE                   NOT NULL,
    music_link      VARCHAR(255),
    music_link_uuid UUID,
    organization_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_stores PRIMARY KEY (id)
);

CREATE TABLE if not exists users
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at                  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_by                  VARCHAR(255)                            NOT NULL,
    created_at                  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by                  VARCHAR(255)                            NOT NULL,
    email                       VARCHAR(254)                            NOT NULL,
    password                    VARCHAR(255),
    role                        VARCHAR(20)                             NOT NULL,
    email_changed               BOOLEAN DEFAULT FALSE                   NOT NULL,
    email_verified              BOOLEAN DEFAULT FALSE                   NOT NULL,
    enabled                     BOOLEAN DEFAULT TRUE                    NOT NULL,
    full_name                   VARCHAR(255),
    company_role                VARCHAR(255),
    email_verification_token_id BIGINT,
    organization_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE music_types
    ADD CONSTRAINT uc_music_types_name UNIQUE (name);

ALTER TABLE stores
    ADD CONSTRAINT uc_stores_musiclink UNIQUE (music_link);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email_verification_token UNIQUE (email_verification_token_id);

ALTER TABLE jingles
    ADD CONSTRAINT FK_JINGLES_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE stores
    ADD CONSTRAINT FK_STORES_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_EMAIL_VERIFICATION_TOKEN FOREIGN KEY (email_verification_token_id) REFERENCES email_verification_tokens (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ORGANIZATION FOREIGN KEY (organization_id) REFERENCES organizations (id);

ALTER TABLE jingle_stores
    ADD CONSTRAINT fk_jinsto_on_jingle FOREIGN KEY (jingle_id) REFERENCES jingles (id);

ALTER TABLE jingle_stores
    ADD CONSTRAINT fk_jinsto_on_store FOREIGN KEY (store_id) REFERENCES stores (id);

ALTER TABLE organization_music_types
    ADD CONSTRAINT fk_orgmustyp_on_music_type FOREIGN KEY (music_type_id) REFERENCES music_types (id);

ALTER TABLE organization_music_types
    ADD CONSTRAINT fk_orgmustyp_on_organization FOREIGN KEY (organization_id) REFERENCES organizations (id);